module.exports = {
  BETHLEHEM_RECOLLECTION_CENTER_ID: 1,
  MALE_GENDER_ID: 1,
  FEMALE_GENDER_ID: 2,
  UNLABELED_GENDER_ID: 3,
  TWO_TO_FOUR_YEARS_ID: 1,
  FIVE_TO_NINE_YEARS_ID: 2,
  TEN_TO_FOURTEEN_YEARS_ID: 3,
  PENDING_STATUS_ID: 1,
  COMPLETED_STATUS_ID: 2,
  DECLINED_STATUS_ID: 3,
  ADMIN_ROLE_TYPE_ID: 1,
  STAFF_ROLE_TYPE_ID: 2,

  // Permissions
  WRITE_QR_CODE_PERMISSION: "WRITE_QR_CODE",
  WRITE_RC_PERMISSION: "WRITE_RC",
  ASSIGN_ROLE_PERMISSION: "ASSIGN_ROLE",
  WRITE_TRANSACTION_PERMISSION: "WRITE_TRANSACTION",
  READ_TRANSACTION_PERMISSION: "READ_TRANSACTION_DETAILS",
  EDIT_TRANSACTION__PERMISSION: "EDIT_TRANSACTION_DETAILS",
  DELETE_TRANSACTION_PERMISSION: "DELETE_TRANSACTION",

  // Mapas
  AGE_MAP: {
    "2-4": 1,
    "5-9": 2,
    "10-14": 3,
    All: [1, 2, 3]
  },
  GENDER_MAP: {
    Male: 1,
    Female: 2,
    Unlabeled: 3,
    All: [1, 2, 3]
  }
};
